from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient

from core.models import VisionAnalysis
from main import app
from orchestrator.graph import build_graph


FIXTURE_PATH = Path(__file__).resolve().parents[1] / "fixtures" / "invoice_sample.pdf"


def _valid_gstin() -> str:
    # Valid GSTIN generated by the same deterministic modulo-36 checksum rule.
    return "27ABCDE1234F1Z0"


def _benford_like_values() -> list[float]:
    counts = {
        1: 301,
        2: 176,
        3: 125,
        4: 97,
        5: 79,
        6: 67,
        7: 58,
        8: 51,
        9: 46,
    }
    values: list[float] = []
    for digit, count in counts.items():
        for idx in range(count):
            values.append(float(f"{digit}{idx + 100}"))
    return values


def test_analyze_endpoint_with_pdf_fixture(monkeypatch) -> None:
    assert FIXTURE_PATH.exists(), f"Missing test fixture: {FIXTURE_PATH}"

    monkeypatch.setattr(
        "sieves.checksum._extract_gstin_candidates_via_llm",
        lambda _text: [_valid_gstin()],
    )
    monkeypatch.setattr(
        "sieves.benford._extract_numbers_via_llm",
        lambda _text: _benford_like_values(),
    )
    monkeypatch.setattr(
        "sieves.vision._call_vision_model",
        lambda _data_url: VisionAnalysis(
            tampering_detected=False,
            risk_level="LOW",
            summary="No visual tampering indicators found.",
            findings=[],
        ),
    )

    # Ensure the test runs with patched nodes and not cached compiled graph closures.
    build_graph.cache_clear()

    with FIXTURE_PATH.open("rb") as fixture_file:
        payload = fixture_file.read()

    client = TestClient(app)
    response = client.post(
        "/analyze",
        files={"invoice": ("invoice_sample.pdf", payload, "application/pdf")},
    )

    assert response.status_code == 200
    body = response.json()
    assert body["status"] == "Completed"
    assert body["final_judgement"] == "VALIDATED"

    forensic_log = body["forensic_log"]
    assert len(forensic_log) == 4
    assert [entry["sieve"] for entry in forensic_log] == [
        "Cryptographic",
        "Checksum",
        "Statistical",
        "Spatial",
    ]
    assert all(entry["result"] in {"PASS", "WARNING"} for entry in forensic_log)
